image: openjdk:11-jdk

variables:

  ANDROID_COMPILE_SDK: "30"

  OUTPUT_DIR: app/build/outputs/

  ANDROID_BUILD_TOOLS: "30.0.3"

  ANDROID_SDK_TOOLS: "7583922"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1


  - export ANDROID_HOME="${PWD}/android-home"

  - install -d $ANDROID_HOME

  - wget --output-document=$ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
  - pushd $ANDROID_HOME
  - unzip -d cmdline-tools cmdline-tools.zip
  - pushd cmdline-tools
  - mv cmdline-tools tools || true
  - popd
  - popd
  - export PATH=$PATH:${ANDROID_HOME}/cmdline-tools/tools/bin/
  - sdkmanager --version
  - yes | sdkmanager --licenses || true
  - sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}"
  - sdkmanager "platform-tools"
  - sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}"
  - chmod +x ./gradlew

stages:
  - debugApk
  - releaseApk
  - releaseBundle

# Make Project
assembleDebug:
  interruptible: true
  stage: debugApk
  script:
    - ./gradlew clean assembleDebug
  retry: 2
  artifacts:
    paths:
      - $OUTPUT_DIR
  only:
    - master

assembleRelease:
  interruptible: true
  stage: releaseApk
  script:
    - echo $KEYSTORE_FILE | base64 -d > keystore.jks
    - ./gradlew clean assembleRelease
  retry: 2
  artifacts:
    paths:
      - $OUTPUT_DIR
  only:
    - master

bundleRelease:   
  interruptible: true
  stage: releaseBundle
  script:
    - echo $KEYSTORE_FILE | base64 -d > keystore.jks
    - echo "keystorePath=../keystore.jks" > keystore.properties
    - echo "keystorePassword=$KEYSTORE_PASSWORD" >> keystore.properties
    - echo "keyAlias=$KEY_ALIAS" >> keystore.properties
    - echo "keyPassword=$KEY_PASSWORD" >> keystore.properties
    - ./gradlew clean bundleRelease 
  artifacts:
    paths:
      - $OUTPUT_DIR
  only:
    - dev