package ru.wb.perevozka.ui.courierdata

enum class CourierDataQueryType {

    SURNAME, NAME, MIDDLE_NAME, INN, PASSPORT_SERIES, PASSPORT_NUMBER, PASSPORT_DATE, PASSPORT_CODE, PASSPORT_ISSUED_BY, PASSPORT_DEPARTMENT_CODE

}