package ru.wb.perevozka.app

object AppExtras {
    const val EXTRA_DIALOG_STYLE = "EXTRA_DIALOG_STYLE"
    const val EXTRA_DIALOG_TITLE = "EXTRA_DIALOG_TITLE"
    const val EXTRA_DIALOG_MESSAGE = "EXTRA_DIALOG_DESCRIPTION"
    const val EXTRA_DIALOG_POSITIVE_BUTTON_TITLE = "EXTRA_DIALOG_POSITIVE_BUTTON_TITLE"
    const val EXTRA_DIALOG_POSITIVE_BUTTON_COLOR = "EXTRA_DIALOG_POSITIVE_BUTTON_COLOR"
    const val EXTRA_DIALOG_NEGATIVE_BUTTON_TITLE = "EXTRA_DIALOG_NEGATIVE_BUTTON_TITLE"
    const val EXTRA_DIALOG_NEGATIVE_BUTTON_COLOR = "EXTRA_DIALOG_NEGATIVE_BUTTON_COLOR"
}